name: bannergen
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pip=22.3.1
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pip:
    - numpy==1.23.5
    - scipy
    - opencv-python
    - opencv-python-headless<4.3
    - albumentations==0.4.3
    - bs4==0.0.1
    - datasets==2.8.0
    - devpi-server==4.8.1
    - diffusers==0.22.2
    - einops==0.3.0
    - facenet_pytorch==2.5.3
    - imageio
    - imageio-ffmpeg==0.4.4
    - imageio==2.9.0
    - jupyter
    - k-diffusion==0.0.16
    - kornia==0.6
    - lmdb==1.2.1
    - mujoco-py==1.50.1.56
    - omegaconf==2.3.0
    - open_clip_torch==2.20.0
    - paddleocr>=2.7.0.3
    - paddlepaddle
    - Pillow==10.1.0
    - pudb==2019.2
    - protobuf>=3.20.0
    - pydevd-pycharm~=212.5457.59
    - pylint
    - pyspng==0.1.0
    - python-Levenshtein
    - pytorch-fid==0.2.1
    - pytorch-lightning==2.0.7
    - pytorch-pretrained-BERT
    - pyyaml
    - requests
    - scikit-image
    - scikit-learn
    - seaborn==0.11.2
    - selenium==4.6.1
    - six
    - stanford-corenlp
    - streamlit>=0.73.1
    - taming-transformers==0.0.1
    - tensorboardX
    - test-tube>=0.7.5
    - timm==0.5.4
    - torch-fidelity==0.3.0
    - torch>=1.10.1
    - torchmetrics
    - tqdm
    - transformers==4.20.1
    - virtualenv
    - wandb
    - fairscale