apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfr-visual-campaign-generator-server
  namespace: sfr-ns-chiachih-chen
  labels:
    app: visual-campaign-generator-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visual-campaign-generator-server
  template:
    metadata:
      labels:
        app: visual-campaign-generator-server
    spec:
      volumes:
      - name: sfr-home-pv-chiachih-chen
        persistentVolumeClaim:
          claimName: sfr-home-pvc-chiachih-chen
      containers:
        - name: dispatcher
          image: "gcr.io/salesforce-research-internal/dispatcher-banner-ads"
          ports:
            - containerPort: 6000
        - name: layoutdetr
          image: "gcr.io/salesforce-research-internal/claude-banner-ads"
          ports:
          - containerPort: 5000
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: "7"
              memory: 45G
          volumeMounts:
            - name: sfr-home-pv-chiachih-chen
              mountPath: "/export/home"
                - name: layoutdetr
        - name: instructpix2pix
          image: "gcr.io/salesforce-research-internal/claude-banner-ads-instructpix2pix"
          ports:
          - containerPort: 4000
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: "7"
              memory: 45G
          volumeMounts:
            - name: sfr-home-pv-chiachih-chen
              mountPath: "/export/home"
      tolerations:
        - key: "gpu_num"
          operator: "Equal"
          value: "2"
          effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: sfr-visual-campaign-generator-server
  labels:
    app: visual-campaign-generator-server
spec:
  ports:
    - port: 8080
      targetPort: 6000
  selector:
    app: visual-campaign-generator-server
  type: LoadBalancer
