version: "3.3"  # optional since v1.27.0
services:
  sd-infinity:
    build: docker
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    command: "/app/docker/entrypoint.sh"
    volumes:
      - .:/app
      - user_home:/home/user
      - cond_env:/opt/conda/envs
      - /dev/shm:/dev/shm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

volumes:
  user_home: {}
  cond_env: {}