MAX_IMG_WIDTH: 2000
MAX_IMG_HEIGHT: 2000
MAX_TIMG_WIDTH: 600
MAX_TIMG_HEIGHT: 400
MIN_BOX_BOX_MARGIN: 16
MIN_BOX_IMG_MARGIN: 16
MIN_JITTER_RATIO: 0.975
MAX_JITTER_RATIO: 1.25

TEXT_CSS_TEMP: "align-items:center;position:absolute;word-wrap:break-word;overflow-wrap:break-word;display:flex;"
JAVASCRIPT: |
    let inner = document.getElementById("{}_in");
    let outer = document.getElementById("{}").style;
    if (inner && outer) {{
        inner.style.fontSize = "{}px"
        resize_to_fit()
    }}
    return inner.style.fontSize;

    function resize_to_fit() {{
        let fontSize = inner.style.fontSize;
        inner.style.fontSize = (parseFloat(fontSize) - 1) + 'px';
        if (inner.clientHeight >= parseFloat(outer.height) - {}) {{
            resize_to_fit();
        }}
    }}
 
